# this workflow may be run if there are leftover files in the runner workspace 
name: Clean up workspace

on: [workflow_dispatch]

# prevent that more than 1 instance of a workflow from this group runs at any given time
concurrency:
  group: default
  cancel-in-progress: false


jobs:
  cleanup:
    name: Cleanup
    runs-on: self-hosted
    steps:
      - name: Cleanup
        uses: AutoModality/action-clean@v1
          
          
