name: Test

on: [workflow_dispatch]

jobs:
  test:
    name: ${{ matrix.testMode }} tests
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        projectPath: [unity]
        testMode: [playmode, editmode]

    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ hashFiles(format('{0}/Assets/**', matrix.projectPath), format('{0}/Packages/**', matrix.projectPath), format('{0}/ProjectSettings/**', matrix.projectPath)) }}
          restore-keys: |
            Library-
      
      # Run tests
      - name: Run ${{ matrix.testMode }} tests
        id: tests
        uses: game-ci/unity-test-runner@v4.1.1
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-results

      # Upload results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.tests.outputs.artifactsPath }}
          path: ${{ steps.tests.outputs.artifactsPath }}
          # if no files match the supplied path, fail job with error
          if-no-files-found: error
  

