name: Test

on: [workflow_dispatch]

jobs:
  test:
    name: Run ${{ matrix.testMode }} tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        projectPath: [unity]
        testMode: [playmode, editmode]
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      - name: Run tests
        uses: game-ci/unity-test-runner@v4.1.1
        id: tests
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          # save test results to ./test-results/
          artifactsPath: ./test-results/${{ matrix.testMode }}-results

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results
          # if no files match the supplied path, fail job with error
          if-no-files-found: error
  

