name: Testing
on: [workflow_dispatch]

jobs:
  test:
    if: |
      github.ref_name == 'develop'
      'cond1' == 'cond1' && 
      'cond2' == 'cond2' && 
      'cond3' == 'cond3'
    

    runs-on: self-hosted
    name: test-job
    steps:
      - name: test-step
        run: echo "Test..."
