name: Testing
on: [workflow_dispatch]

jobs:

  dep:
    runs-on: self-hosted
    name: dependency
    steps:
      - name: dep-step
        run: echo "Dependency..."

  test:
    needs: [dep]
    if: |
      github.ref_name == 'develop' && 
      needs.dep.result == 'success' &&
      github.event_name == 'workflow_dispatch' &&
      'cond1' == 'cond1' && 
      'cond2' == 'cond2' && 
      'cond3' == 'cond3'
    

    runs-on: self-hosted
    name: test-job
    steps:
      - name: test-step
        run: echo "Test..."
